# .github/workflows/build-apk.yml

name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 1) Bring in sdkmanager & platform-tools only
      - name: Setup Android SDK (cmdline-tools + platform-tools)
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: '11.0'    # ensure we get sdkmanager
          packages: |
            platform-tools                # only install adb, fastboot, etc.

      # 2) Now use sdkmanager directly to grab API-36 and Build-Tools 36.0.0
      - name: Install Android API-36 and Build-Tools
        run: |
          yes | sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip autoconf libtool \
            pkg-config zlib1g-dev libncurses-dev libffi-dev libssl-dev cmake

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "cython<3.0"
          python -m pip install buildozer

      - name: Create .env file from Secret
        run: echo "PICOVOICE_ACCESS_KEY=${{ secrets.PICOVOICE_ACCESS_KEY }}" > .env

      - name: Build with Buildozer
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-assistant-apk
          path: bin/*.apk
