name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      ANDROID_HOME: /usr/local/lib/android/sdk
      JAVA_HOME: /opt/hostedtoolcache/Java_Zulu_jdk/17.0.15-6/x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # Install sdkmanager + adb/fastboot
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.2
        with:
          cmdline-tools-version: '12.0'
          packages: |
            platform-tools
            platforms;android-34
            build-tools;34.0.0
          accept-android-sdk-licenses: true

      # Mirror that SDK into Buildozer's sandbox
      - name: Seed Buildozer SDK folder
        run: |
          mkdir -p ~/.buildozer/android/platform
          ln -sf "$ANDROID_SDK_ROOT" ~/.buildozer/android/platform/android-sdk

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ant \
            build-essential git zip unzip autoconf libtool \
            pkg-config zlib1g-dev libncurses-dev libffi-dev libssl-dev cmake

      - name: Install Python deps
        run: |
          pip install --upgrade pip
          pip install "cython<3.0" buildozer

      - name: Create .env from Secret
        run: |
          echo "PICOVOICE_ACCESS_KEY=${{ secrets.PICOVOICE_ACCESS_KEY }}" > .env

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-assistant-apk
          path: bin/*.apk
