# .github/workflows/build-apk.yml (Final Corrected Version)

name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip openjdk-17-jdk autoconf libtool \
            pkg-config zlib1g-dev libncurses-dev libffi-dev libssl-dev cmake

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "cython<3.0"
          python -m pip install buildozer

      - name: Create .env file from Secret
        run: echo "PICOVOICE_ACCESS_KEY=${{ secrets.PICOVOICE_ACCESS_KEY }}" > .env

      # --- THIS IS THE CRUCIAL FIX ---
      - name: Accept Android SDK licenses
        run: |
          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build with Buildozer
        # We need to run buildozer with sudo because of how GitHub Actions permissions work
        # And we need to give it access to the current directory
        run: sudo buildozer -v --workdir . android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-assistant-apk
          path: bin/*.apk
