# .github/workflows/build-apk.yml (Final Version using setup-android Action)

name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      # The setup-java action is often required by setup-android
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # --- THIS IS THE NEW, ROBUST SOLUTION ---
      # This action reliably sets up the Android SDK and accepts all licenses
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3.2.1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      
      # We no longer need to install openjdk-17-jdk manually as setup-java handles it
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential git zip unzip autoconf libtool \
            pkg-config zlib1g-dev libncurses-dev libffi-dev libssl-dev cmake

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install "cython<3.0"
          python -m pip install buildozer

      - name: Create .env file from Secret
        run: echo "PICOVOICE_ACCESS_KEY=${{ secrets.PICOVOICE_ACCESS_KEY }}" > .env

      - name: Build with Buildozer
        # Run as the current user, no sudo needed
        run: buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-assistant-apk
          path: bin/*.apk
