# .github/workflows/build-apk.yml

name: Build Kivy APK with Buildozer

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      JAVA_HOME:        /opt/hostedtoolcache/Java_Zulu_jdk/17.0.15-6/x64

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 1) Install only cmdline-tools & platform-tools so we get sdkmanager
      - name: Setup Android SDK (core only)
        uses: android-actions/setup-android@v3.2.2
        with:
          cmdline-tools-version: '12.0'
          packages: |
            platform-tools
          accept-android-sdk-licenses: true      # auto-accept the core tools licence
          log-accepted-android-sdk-licenses: false

      # 2) Now accept EVERY Android SDK licence (this creates /licenses files)
      - name: Accept all SDK licences
        run: |
          yes | sdkmanager --sdk_root=${ANDROID_SDK_ROOT} --licenses

      # 3) Install exactly the API + build-tools you need
      - name: Install Android API-36 & Build-Tools 36.0.0
        run: |
          sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            ant \
            build-essential git zip unzip autoconf libtool \
            pkg-config zlib1g-dev libncurses-dev libffi-dev libssl-dev cmake

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install "cython<3.0"
          pip install buildozer

      - name: Create .env from Secret
        run: |
          echo "PICOVOICE_ACCESS_KEY=${{ secrets.PICOVOICE_ACCESS_KEY }}" > .env

      - name: Build with Buildozer
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-assistant-apk
          path: bin/*.apk
